# Proje genel ayarları
project:
  name: climateWatch
  version: 1.0

# Veri yolları
data_paths:
  gdelt: data_storage/gdelt
  climate: data_storage/climate
  disasters: data_storage/disasters
  policies: data_storage/policies
  summits: data_storage/summits
  processed: data_storage/processed
  logs: logs
  kaggle: data_storage/kaggle

# Tarih aralıkları (test için sınırlandırılmış)
date_range:
  start_date: '2024-01-01'
  end_date: '2024-01-02'  # Sadece 1 günlük veri

# Anahtar kelimeler (haber filtreleme için)
keywords:
  - CLIMATE
  - ENVIRONMENT
  - WEATHER
  - GLOBAL WARMING
  - CO2
  - CARBON
  - EMISSION
  - SUSTAINABILITY

# MongoDB ayarları
mongodb:
  host: mongodb
  port: 27017
  db: climatewatch
  collection_gdelt: gdelt_events

# Spark ayarları (test için optimize edilmiş)
spark:
  app_name: climateWatch ETL Test
  master: local[2]  # Daha az thread kullanımı
  executor_memory: 1g
  driver_memory: 1g
  max_result_size: 1g

# Kaggle ayarları
kaggle_dataset: climate
kaggle_max_datasets: 3

# Diğer parametreler
general:
  log_file: logs/pipeline.log
  test_mode: true  # Test modu aktif 