version: '3.8'

services:
  jupyter:
    image: jupyter/pyspark-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    depends_on:
      - spark-master
    networks:
      - climate_network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - climate_network

  hdfs-namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    environment:
      - CLUSTER_NAME=climatewatch
    ports:
      - "9870:9870"
    volumes:
      - ./data_storage/hdfs/namenode:/hadoop/dfs/name
    env_file:
      - ./docker/hadoop.env

  hdfs-datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    environment:
      - CLUSTER_NAME=climatewatch
    ports:
      - "9864:9864"
    volumes:
      - ./data_storage/hdfs/datanode:/hadoop/dfs/data
    env_file:
      - ./docker/hadoop.env
    depends_on:
      - hdfs-namenode

  spark-master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_IPS=spark-master
      - SPARK_PUBLIC_DNS=spark-master
    ports:
      - "8081:8080"
      - "7077:7077"
    networks:
      - climate_network

  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_IPS=spark-worker
      - SPARK_PUBLIC_DNS=spark-worker
    depends_on:
      - spark-master
    networks:
      - climate_network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - climate_network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - climate_network

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    environment:
      - HIVE_METASTORE_DB_TYPE=postgres
    ports:
      - "9083:9083"
    depends_on:
      - hdfs-namenode
      - hdfs-datanode
    volumes:
      - ./data_storage/hive:/opt/hive/data

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    environment:
      - HIVE_METASTORE_DB_TYPE=postgres
    ports:
      - "10000:10000"
    depends_on:
      - hive-metastore
    volumes:
      - ./data_storage/hive:/opt/hive/data

  hbase:
    image: harisekhon/hbase:1.2
    ports:
      - "16010:16010"
      - "2182:2182"
    environment:
      - HBASE_MANAGES_ZK=false
    depends_on:
      - hdfs-namenode
      - hdfs-datanode
    volumes:
      - ./data_storage/hbase:/data/hbase

  pyspark-jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: pyspark-jupyter
    ports:
      - "8889:8888"
    volumes:
      - ./:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    networks:
      - climate_network

networks:
  climate_network:
    driver: bridge

volumes:
  mongodb_data: 